import { GeistMono } from "geist/font/mono"
import { GeistSans } from "geist/font/sans"
import type { Metadata, Viewport } from "next"

import "./globals.css"

import { ThemeColorSync } from "@/components/pwa/theme-color-sync"
import { AnalyticsProvider } from "@/components/shared/analytics-provider"
import { ThemeProvider } from "@/components/theme-provider"
import { Toaster } from "@/components/ui/sonner"
import { env } from "@/lib/env"
import { APPLE_TOUCH_ICON, iconPath, THEME_COLORS } from "@/lib/pwa/icons"
import { APP_DESCRIPTION } from "@/lib/pwa/manifest"

export function generateMetadata(): Metadata {
  return {
    metadataBase: new URL(env.NEXT_PUBLIC_APP_URL),
    title: { default: env.APP_NAME, template: `%s · ${env.APP_NAME}` },
    description: APP_DESCRIPTION,
    applicationName: env.APP_NAME,
    // app/favicon.ico and app/icon.svg are linked by Next's file conventions; the PNGs are
    // generated by `pnpm pwa:icons` (lib/pwa/icons.ts).
    icons: {
      apple: [
        {
          url: iconPath(APPLE_TOUCH_ICON.file),
          sizes: `${APPLE_TOUCH_ICON.size}x${APPLE_TOUCH_ICON.size}`,
          type: "image/png",
        },
      ],
    },
    // Added to an iPhone's home screen, the app opens full screen like a native one
    // (app/manifest.ts). The "default" status bar keeps the clock readable in both themes: iOS
    // draws it above the page, so nothing slides under it. ("black-translucent" would put white
    // text over the light theme.) The bars still pad with env(safe-area-inset-*), which covers
    // the notch in landscape and the home indicator.
    appleWebApp: { capable: true, title: env.APP_NAME, statusBarStyle: "default" },
    formatDetection: { telephone: false, email: false, address: false },
  }
}

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  // Lets the layout reach under the notch and home indicator; the top and bottom bars pad with
  // env(safe-area-inset-*) (app/globals.css). Pinch zoom stays allowed (accessibility).
  viewportFit: "cover",
  // The browser and status bar follow the page background of each theme.
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: THEME_COLORS.light },
    { media: "(prefers-color-scheme: dark)", color: THEME_COLORS.dark },
  ],
  colorScheme: "light dark",
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html
      lang="en"
      className={`${GeistSans.variable} ${GeistMono.variable}`}
      suppressHydrationWarning
    >
      <body className="min-h-svh font-sans antialiased">
        <AnalyticsProvider>
          <ThemeProvider>
            {children}
            {/* The browser and status bar follow the theme chosen in the app, on every page. */}
            <ThemeColorSync />
            {/* Toasts sit above the app's bottom tab bar (--sticky-bottom, 0 from md up) at every
                width: sonner's mobileOffset only applies up to 600px, the tab bar up to 767px. */}
            <Toaster
              richColors
              closeButton
              offset={{ bottom: "calc(24px + var(--sticky-bottom, 0px))" }}
              mobileOffset={{ bottom: "calc(16px + var(--sticky-bottom, 0px))" }}
            />
          </ThemeProvider>
        </AnalyticsProvider>
      </body>
    </html>
  )
}
